---
title: "Unique Count for Sample ASVs and Reads for Combo Dataset"
output: html_notebook
---


# Load libraries
```{r}
library(dplyr)
library(tidyverse)
library(readxl)
```

# Set working directory
```{r}
setwd("C:/Users/Jessica/Desktop/Combo/Classification Count")
getwd()
```

# Library
```{r}
library(dplyr)
library(tidyverse)
library(readxl)
```

# Load data
```{r}
data <- read_excel("combo.xlsx", sheet="Sheet1")
```

# Summarize ASvs and Reads for Kingdom
```{r}
kingdom <- data %>%
  group_by(Kingdom) %>%
  summarize(count_number = n(), sum_reads = sum(grandtotal_reads))

kingdom
```

# Summarize ASvs and Reads for Phylum
```{r}
phylum <- data %>%
  group_by(Phylum) %>%
  summarize(count_number = n(), sum_reads = sum(grandtotal_reads))

phylum
```


# Summarize ASVs and Reads for Class
```{r}
class <- data %>%
  group_by(Class) %>%
  summarize(count_number = n(), sum_reads = sum(grandtotal_reads))

class
```

# Summarize ASVs and Reads for Order
```{r}
order <- data %>%
  group_by(Order) %>%
  summarize(count_number = n(), sum_reads = sum(grandtotal_reads))

order
```

# Summarize ASVs and Reads for Family
```{r}
family <- data %>%
  group_by(Family) %>%
  summarize(count_number = n(), sum_reads = sum(grandtotal_reads))

family
```

# Summarize ASVs and Reads for Genus
```{r}
genus <- data %>%
  group_by(Genus) %>%
  summarize(count_number = n(), sum_reads = sum(grandtotal_reads))

genus
```


